---
- hosts:
    - raspberry-pis
  tasks:
    - name: "Install Fourletter phat package"
      package:
        name: python3-fourletterphat
        state: present
      become: true

    - name: "Make sure the main folder exists"
      file:
        path: "{{ pidi_script_folder }}"
        state: directory

    - name: "Copy the main script"
      copy:
        src: pi4display.py
        dest: "{{ pidi_script_folder }}/pi4display.py"
      tags: ["script"]

    - name: "Copy runtime constants"
      template:
        src: constants.py.j2
        dest: "{{ pidi_script_folder }}/constants.py"
      tags: ["script"]

    - name: Install systemd unit file
      template:
        src: pidisplay.service.j2
        dest: /etc/systemd/system/pidisplay.service
        mode: 0644
      become: true

    - name: Enable systemd service
      systemd:
        name: pidisplay
        state: restarted
        enabled: yes
        daemon_reload: yes
      become: true

  vars_files:
    - vars/main.yaml
