---
- hosts:
    - raspberry-pis
  tasks:
    - name: "Install Fourletter phat package"
      package:
        name: python3-fourletterphat
        state: present
      become: true

    - name: "Copy the main script"
      copy:
        src: example.py
        dest: "{{ pidi_script_path }}"

    - name: Install systemd unit file
      copy:
        src: pidisplay.service
        dest: /etc/systemd/system/pidisplay.service
        mode: 0644
      become: true

    - name: Enable systemd service
      systemd:
        name: pidisplay
        state: restarted
        enabled: yes
        daemon_reload: yes
      become: true

  vars_files:
    - vars/main.yaml
